name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend:
    name: Build, Test, and Package Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: ./mvnw test

      - name: Build and package application
        run: ./mvnw clean package

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: target/*.jar